export function exportToPDF(
  analysis: string,
  filename: string,
  query: string
): void {
  // Create a new window for printing
  const printWindow = window.open('', '_blank')

  if (!printWindow) {
    alert('Please allow popups to export PDF')
    return
  }

  // Generate HTML content
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Financial Analysis - ${filename}</title>
      <style>
        @page {
          margin: 2cm;
        }
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
          line-height: 1.6;
          color: #1f2937;
          max-width: 800px;
          margin: 0 auto;
          padding: 20px;
        }
        .header {
          border-bottom: 3px solid #2563eb;
          padding-bottom: 20px;
          margin-bottom: 30px;
        }
        .header h1 {
          color: #2563eb;
          margin: 0 0 10px 0;
          font-size: 28px;
        }
        .header .subtitle {
          color: #6b7280;
          font-size: 14px;
        }
        .meta {
          background: #f3f4f6;
          padding: 15px;
          border-radius: 8px;
          margin-bottom: 30px;
        }
        .meta-item {
          margin-bottom: 8px;
        }
        .meta-label {
          font-weight: 600;
          color: #374151;
        }
        .section {
          margin-bottom: 25px;
        }
        .section h2 {
          color: #1f2937;
          font-size: 18px;
          margin-bottom: 12px;
          border-left: 4px solid #2563eb;
          padding-left: 12px;
        }
        .content {
          white-space: pre-wrap;
          font-size: 14px;
          line-height: 1.8;
        }
        .footer {
          margin-top: 40px;
          padding-top: 20px;
          border-top: 1px solid #e5e7eb;
          text-align: center;
          color: #9ca3af;
          font-size: 12px;
        }
        @media print {
          body {
            padding: 0;
          }
          .no-print {
            display: none;
          }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>📊 Financial Analysis Report</h1>
        <p class="subtitle">Generated by Financial Analyzer</p>
      </div>

      <div class="meta">
        <div class="meta-item">
          <span class="meta-label">File:</span> ${filename}
        </div>
        <div class="meta-item">
          <span class="meta-label">Date:</span> ${new Date().toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'long',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit'
          })}
        </div>
        <div class="meta-item">
          <span class="meta-label">Query:</span> ${query}
        </div>
      </div>

      <div class="section">
        <h2>Analysis</h2>
        <div class="content">${analysis.replace(/\n/g, '<br>')}</div>
      </div>

      <div class="footer">
        <p>This report was generated automatically. Please verify all information before making financial decisions.</p>
      </div>

      <div class="no-print" style="margin-top: 30px; text-align: center;">
        <button onclick="window.print()" style="
          background: #2563eb;
          color: white;
          border: none;
          padding: 12px 24px;
          border-radius: 8px;
          cursor: pointer;
          font-size: 16px;
          font-weight: 600;
        ">
          🖨️ Print / Save as PDF
        </button>
        <button onclick="window.close()" style="
          background: #e5e7eb;
          color: #1f2937;
          border: none;
          padding: 12px 24px;
          border-radius: 8px;
          cursor: pointer;
          font-size: 16px;
          font-weight: 600;
          margin-left: 10px;
        ">
          ❌ Close
        </button>
      </div>
    </body>
    </html>
  `

  printWindow.document.write(htmlContent)
  printWindow.document.close()
}
